-- ============================================================================
-- schema_snapshot(): the whole database structure as one SQL script.
--
-- It returns everything needed to rebuild the store's database in a new, empty Supabase project:
-- extensions, tables, keys and links, indexes, functions, triggers (also the one that creates a
-- customer profile on sign-up), row-level security rules, permissions, the picture storage bucket
-- and its rules, and the nightly clean-up job. Data is NOT included (that is the backup .zip).
--
-- Used by:
--   * Admin → Backup: every backup .zip contains this script as schema.sql
--   * supabase/setup_all.sql: the same script saved in the project (made with this function)
--
-- Only the store owner can call it (or the database owner in the SQL Editor).
-- Safe to run more than once. In the Supabase SQL Editor, paste the WHOLE file and press Run.
-- ============================================================================
CREATE OR REPLACE FUNCTION public.schema_snapshot()
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
-- Only pg_catalog, so every name in the output is written with its schema (public.…, extensions.…).
SET search_path = pg_catalog
AS $snapshot$
DECLARE
  out text;
  part text;
  nl constant text := E'\n';
BEGIN
  IF session_user NOT IN ('postgres', 'supabase_admin') AND NOT coalesce(public.admin_has('backup'), false) THEN
    RAISE EXCEPTION 'Only the store owner can read the database structure.';
  END IF;

  out := '-- ============================================================================' || nl
      || '-- Clever Toys: complete database structure (made ' || to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') || ' UTC).' || nl
      || '-- Rebuilds the store''s database in a new, empty Supabase project. Data is not included:' || nl
      || '-- after running this, restore a backup in Admin → Backup.' || nl
      || '-- In the Supabase SQL Editor, paste the WHOLE file and press Run. Safe to run more than once.' || nl
      || '-- ============================================================================' || nl
      || 'SET check_function_bodies = off;' || nl || nl;

  -- 1. Extensions (search, ids, the nightly job…)
  SELECT string_agg(format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;', e.extname, n.nspname), nl ORDER BY e.extname)
    INTO part
  FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
  WHERE e.extname NOT IN ('plpgsql', 'supabase_vault', 'pg_graphql', 'pgsodium');
  out := out || '-- 1. Extensions' || nl || 'CREATE SCHEMA IF NOT EXISTS extensions;' || nl || coalesce(part, '') || nl || nl;

  -- 2. Tables and their columns
  SELECT string_agg(format(E'CREATE TABLE IF NOT EXISTS public.%I (\n%s\n);', c.relname, cols.def), nl || nl ORDER BY c.relname)
    INTO part
  FROM pg_class c
  CROSS JOIN LATERAL (
    SELECT string_agg(
      '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
      || CASE a.attidentity WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY' WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY' ELSE '' END
      || CASE WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS (' || pg_get_expr(d.adbin, d.adrelid) || ') STORED'
              WHEN d.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid) ELSE '' END
      || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
      E',\n' ORDER BY a.attnum) AS def
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
  ) cols
  WHERE c.relnamespace = 'public'::regnamespace AND c.relkind = 'r';
  out := out || '-- 2. Tables' || nl || coalesce(part, '') || nl || nl;

  -- 3. Keys, checks and links between tables (primary keys first, links last)
  SELECT string_agg(
      format('DO $c$ BEGIN ALTER TABLE public.%I ADD CONSTRAINT %I %s; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $c$;',
             cl.relname, co.conname, pg_get_constraintdef(co.oid)),
      nl ORDER BY CASE co.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'c' THEN 3 WHEN 'x' THEN 4 ELSE 5 END, cl.relname, co.conname)
    INTO part
  FROM pg_constraint co JOIN pg_class cl ON cl.oid = co.conrelid
  WHERE cl.relnamespace = 'public'::regnamespace AND cl.relkind = 'r' AND co.contype IN ('p', 'u', 'c', 'f', 'x');
  out := out || '-- 3. Keys, checks and links' || nl || coalesce(part, '') || nl || nl;

  -- 4. Indexes (the ones not already made by a key above)
  SELECT string_agg(
      regexp_replace(pg_get_indexdef(i.indexrelid), '^CREATE (UNIQUE )?INDEX ', 'CREATE \1INDEX IF NOT EXISTS ') || ';',
      nl ORDER BY ic.relname)
    INTO part
  FROM pg_index i
  JOIN pg_class ic ON ic.oid = i.indexrelid
  JOIN pg_class t ON t.oid = i.indrelid
  WHERE t.relnamespace = 'public'::regnamespace
    AND NOT EXISTS (SELECT 1 FROM pg_constraint k WHERE k.conindid = i.indexrelid);
  out := out || '-- 4. Indexes' || nl || coalesce(part, '') || nl || nl;

  -- 5. Functions (search, orders, stock, admin roles, clean-up…), without the ones extensions bring
  SELECT string_agg(pg_get_functiondef(p.oid) || ';', nl ORDER BY p.proname, p.oid::regprocedure::text)
    INTO part
  FROM pg_proc p
  WHERE p.pronamespace = 'public'::regnamespace AND p.prokind IN ('f', 'p')
    AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid = 'pg_proc'::regclass AND d.objid = p.oid AND d.deptype = 'e');
  out := out || '-- 5. Functions' || nl || coalesce(part, '') || nl;

  -- 6. Who may call each function
  SELECT string_agg(
      format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated;', p.oid::regprocedure)
      || coalesce((
        SELECT string_agg(format(' GRANT EXECUTE ON FUNCTION %s TO %s;', p.oid::regprocedure, CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE quote_ident(r.rolname) END), '' ORDER BY r.rolname)
        FROM aclexplode(p.proacl) a LEFT JOIN pg_roles r ON r.oid = a.grantee
        WHERE a.privilege_type = 'EXECUTE' AND (a.grantee = 0 OR r.rolname IN ('anon', 'authenticated', 'service_role'))
      ), ''),
      nl ORDER BY p.oid::regprocedure::text)
    INTO part
  FROM pg_proc p
  WHERE p.pronamespace = 'public'::regnamespace AND p.prokind IN ('f', 'p') AND p.proacl IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid = 'pg_proc'::regclass AND d.objid = p.oid AND d.deptype = 'e');
  out := out || '-- 6. Function permissions' || nl || coalesce(part, '') || nl || nl;

  -- 7. Row-level security and table permissions
  SELECT string_agg(format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', relname), nl ORDER BY relname)
    INTO part
  FROM pg_class WHERE relnamespace = 'public'::regnamespace AND relkind = 'r' AND relrowsecurity;
  out := out || '-- 7. Row-level security and table permissions' || nl || coalesce(part, '') || nl;
  SELECT string_agg(
      format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated;', c.relname)
      || coalesce((
        SELECT string_agg(format(' GRANT %s ON TABLE public.%I TO %I;', g.privs, c.relname, g.rolname), '' ORDER BY g.rolname)
        FROM (SELECT r.rolname, string_agg(a.privilege_type, ', ' ORDER BY a.privilege_type) AS privs
              FROM aclexplode(c.relacl) a JOIN pg_roles r ON r.oid = a.grantee
              WHERE r.rolname IN ('anon', 'authenticated') GROUP BY r.rolname) g
      ), ''),
      nl ORDER BY c.relname)
    INTO part
  FROM pg_class c WHERE c.relnamespace = 'public'::regnamespace AND c.relkind = 'r' AND c.relacl IS NOT NULL;
  out := out || coalesce(part, '') || nl || nl;

  -- 8. Security rules (who can read and change what), for the store tables and the picture storage
  SELECT string_agg(
      format('DO $p$ BEGIN CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s%s%s; EXCEPTION WHEN duplicate_object THEN NULL; END $p$;',
             policyname, schemaname, tablename, permissive, cmd,
             (SELECT string_agg(CASE WHEN r = 'public' THEN 'PUBLIC' ELSE quote_ident(r) END, ', ') FROM unnest(roles) AS r),
             CASE WHEN qual IS NOT NULL THEN ' USING (' || qual || ')' ELSE '' END,
             CASE WHEN with_check IS NOT NULL THEN ' WITH CHECK (' || with_check || ')' ELSE '' END),
      nl ORDER BY schemaname, tablename, policyname)
    INTO part
  FROM pg_policies WHERE schemaname = 'public' OR (schemaname = 'storage' AND tablename = 'objects');
  out := out || '-- 8. Security rules' || nl || coalesce(part, '') || nl || nl;

  -- 9. Triggers (stock sync, history, activity log, customer profile on sign-up…)
  SELECT string_agg(regexp_replace(pg_get_triggerdef(t.oid), '^CREATE TRIGGER ', 'CREATE OR REPLACE TRIGGER ') || ';', nl ORDER BY t.tgrelid::regclass::text, t.tgname)
    INTO part
  FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
  WHERE NOT t.tgisinternal AND (c.relnamespace = 'public'::regnamespace OR t.tgrelid = 'auth.users'::regclass);
  out := out || '-- 9. Triggers' || nl || coalesce(part, '') || nl || nl;

  -- 9b. Event triggers that run store functions (e.g. turning on row-level security for new tables)
  SELECT string_agg(
      format('DO $e$ BEGIN CREATE EVENT TRIGGER %I ON %s%s EXECUTE FUNCTION %s(); EXCEPTION WHEN duplicate_object OR insufficient_privilege THEN NULL; END $e$;',
             et.evtname, et.evtevent,
             CASE WHEN et.evttags IS NOT NULL THEN ' WHEN TAG IN (' || (SELECT string_agg(quote_literal(tag), ', ') FROM unnest(et.evttags) AS tag) || ')' ELSE '' END,
             et.evtfoid::regproc),
      nl ORDER BY et.evtname)
    INTO part
  FROM pg_event_trigger et JOIN pg_proc p ON p.oid = et.evtfoid
  WHERE p.pronamespace = 'public'::regnamespace;
  out := out || '-- 9b. Event triggers' || nl || coalesce(part, '') || nl || nl;

  -- 10. Picture storage
  SELECT string_agg(format('INSERT INTO storage.buckets (id, name, public) VALUES (%L, %L, %s) ON CONFLICT (id) DO NOTHING;', id, name, CASE WHEN public THEN 'true' ELSE 'false' END), nl ORDER BY id)
    INTO part FROM storage.buckets;
  out := out || '-- 10. Picture storage' || nl || coalesce(part, '') || nl || nl;

  -- 11. Scheduled jobs (nightly clean-up)
  IF to_regclass('cron.job') IS NOT NULL THEN
    EXECUTE $q$SELECT string_agg(format('SELECT cron.schedule(%L, %L, %L);', jobname, schedule, command), E'\n' ORDER BY jobname) FROM cron.job$q$ INTO part;
    out := out || '-- 11. Scheduled jobs' || nl || coalesce(part, '') || nl || nl;
  END IF;

  -- 12. The settings row every page reads, then refresh the API
  out := out || '-- 12. Store settings row and API refresh' || nl
      || 'INSERT INTO public.store_settings (id) VALUES (''default'') ON CONFLICT (id) DO NOTHING;' || nl
      || 'NOTIFY pgrst, ''reload schema'';' || nl;
  RETURN out;
END;
$snapshot$;

REVOKE ALL ON FUNCTION public.schema_snapshot() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.schema_snapshot() TO authenticated;
